global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tai-reference-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']

  - job_name: 'payment-system'
    static_configs:
      - targets: ['payment-system:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'deployment-system'
    static_configs:
      - targets: ['deployment-system:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "/etc/prometheus/alert_rules.yml"
