apiVersion: v1
kind: ConfigMap
metadata:
  name: tai-config
  namespace: {{ .Values.namespace }}
  labels:
    app: tai
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
{{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
{{- end }}
