{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.api.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.apiPort }}
    targetPort: {{ .Values.api.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.api.name }}
{{- end }}
---
{{- if .Values.cache.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cache.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.cache.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.cache.name }}
  ports:
  - port: {{ .Values.cache.port }}
    targetPort: {{ .Values.cache.port }}
    protocol: TCP
    name: redis
{{- end }}
