global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tps-reference-system'

scrape_configs:
  - job_name: 'tps-system'
    static_configs:
      - targets: ['tps-system:9090']
        labels:
          service: 'tps-reference'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

remote_write:
  - url: "http://prometheus:9090/api/v1/write"
    queue_config:
      capacity: 10000
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 500
      batch_send_wait_time: 5s
      min_backoff: 30ms
      max_backoff: 100ms
